(import (chicken bitwise) (chicken condition) (chicken file posix) 
        (chicken foreign) (chicken io) (chicken string) (srfi 4))

(define-syntax λ (syntax-rules () ((_ . ω) (lambda . ω))))
(define-syntax ? (syntax-rules () ((_ . ω) (if . ω))))
(define-syntax ← (syntax-rules () ((_ . ω) (define . ω))))
(define-syntax ∃ (syntax-rules () ((_ . ω) (let* . ω))))
(define-syntax either
  (syntax-rules ()
    ((_ f ...)
     (∃ ((ω (condition-case ((λ () f ...))
              (e (exn) (left (get-condition-property e 'exn 'message))))))
       (? (left? ω) ω (right ω))))))
(define-syntax for
  (syntax-rules (←)
    ((_ (← α β) ω ...) (>>= (λ (α) (for ω ...)) β))
    ((_ (  α β) ω ...) (>>= (λ (α) (for ω ...)) (right β)))
    ((_             ω) (right ω))))

(← NRPN-CMDS '((p1 0   0 63 64)
               (l1 1 -63 63 64)
               (y  2   0  3 64)
               (q1 3   0 63 64)))

(← ↑ car) (← ↓ cdr) (← ↑↓ cadr) (← ∘ compose) (← ≡ equal?) (← ∅ '()) 
(← ∅? null?) (← ρ length) (← ◇ conc) (← ⊂ cons) (← ∀ map)
(← (∧ ω α) (and ω α))
(← (∨ ω α) (or ω α))
(← (I ω) ω)
(← (K ω) (λ (α) ω))
(← (C f) (λ (ω) (λ (α) (f ω α))))
(← (S g f) (λ (ω) (g ω (f ω))))
(← (J h g f) (λ (ω) (h (g ω) (f ω))))
(← (right ω) `(R ,ω))
(← (left ω) `(L ,ω))
(← (right? ω) (? (list? ω) (? (≡ 2 (ρ ω)) (≡ 'R (↑ ω)) #f) #f))
(← (left? ω) (? (list? ω) (? (≡ 2 (ρ ω)) (≡ 'L (↑ ω)) #f) #f))
(← (either? ω) (? ((J ∨ left? right?) ω) ω (left (◇ "not an either: " ω))))
(← (get Fω) (? (right? Fω) (↑↓ Fω) (error (↑↓ Fω))))
(← (guard p) (? p (right ∅) (left ∅)))
(← (⊙ f Fω) (∃ ((α (either? Fω))) (? (right? α) (right (f (↑↓ α))) α)))
(← (_⊙ f Fω) (∃ ((α (either? Fω))) (? (left? α) (left (f (↑↓ α))) α)))
(← (⊙⊙ f g Fω) (⊙ f (_⊙ g Fω)))
(← (⊥ Fω) (either (get (get Fω))))
(← (>>= f Fω) (⊥ (⊙ f Fω)))
(← (● Ff Fω) (>>= (λ (ω) (⊙ (λ (f) (f ω)) Ff)) Fω))
(← (*> Fω Fα) (>>= (K Fα) Fω))
(← ($> Fω α) (*> Fω (right α)))
(← (lift2 f Fα Fω) (● (⊙ (C f) Fα) Fω))
(← (sequence Fω) (foldr (λ (x acc) (lift2 ⊂ x acc)) (right ∅) Fω))
(← (traverse f Fω) (sequence (∀ f Fω)))
(← (ι n Fω) (either (list-ref Fω n)))
; BREAK: can't get this part right
;(← (s⊥ f e ω) (∃ ((α (>>= guard (either (f ω))))) (⊙⊙ I (λ (x) (◇ x " " ω)) α)))
;(← (s⊥ f e ω) (∃ ((α (either (f ω)))) (⊙⊙ I (K (◇ e " " ω)) α)))
;(← (s⊥ f e ω) (for (← α (either f ω)) (← _ (guard α)) α))
(← (s⊥ f ω) (for (← α (either f ω)) (← _ (guard α)) α))
(← (s⊥n ω) (s⊥ string->number ω))
(← (s⊥x ω) (s⊥ string->symbol ω))
(← (∈ ω k) (∃ ((α (assoc k ω))) (⊙⊙ (K (↓ α)) (K (◇ "cmd not found: " k)) (guard α))))

; this works though
(← zzz (_⊙ (K "err")
    (for (← α (either (string->number "a")))
         (← _ (guard α))
         α)))

